### ISSUE TITLE
Move Gifts details to info page

### ISSUE THREAD

**Issue by alanna** [mixmix/wedding#6]
I think it might be a bit presumptuous/uncouth to make Gifts such an in your face section on the main navigation. Let's just put it on the bottom of the "info" page.

**Comment by mixmix** [comment]
There is no 'info' page
Do you mean about ?

**Comment by mixmix** [comment]
oh i see logistics = info. 

I tried it and it looks cluttered. Would like to talk about this, think it is a good idea for it to be top level as  Ithink about it
